--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 29 2016 21:14
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Address'   
-- AddressId       :  
-- Country         :  
-- Town            :  
-- Street          :  
-- unnamed         :  
--
CREATE TABLE Address (
    AddressId      BIGINT IDENTITY(1,1) NOT NULL,
    Country        NVARCHAR(500) NOT NULL,
    Town           NVARCHAR(500) NOT NULL,
    Street         NVARCHAR(500) NOT NULL,
    unnamed        NVARCHAR(500) NOT NULL,
CONSTRAINT pk_Address PRIMARY KEY CLUSTERED (AddressId))
GO

--
-- Create Table    : 'Person'   
-- PersonId        :  
-- FirstName       :  
-- MiddelName      :  
-- LastName        :  
-- unnamed         :  
-- AddressId       :  (references Address.AddressId)
--
CREATE TABLE Person (
    PersonId       BIGINT IDENTITY(1,1) NOT NULL,
    FirstName      NVARCHAR(500) NOT NULL,
    MiddelName     NVARCHAR(500) NOT NULL,
    LastName       NVARCHAR(500) NOT NULL,
    unnamed        NVARCHAR(500) NOT NULL,
    AddressId      BIGINT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonId),
CONSTRAINT fk_Person FOREIGN KEY (AddressId)
    REFERENCES Address (AddressId)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Phone'   
-- PhoneId         :  
-- Phonenumber     :  
-- CountryCode     :  
-- PhoneType       :  
-- PersonId        :  (references Person.PersonId)
--
CREATE TABLE Phone (
    PhoneId        BIGINT IDENTITY(1,1) NOT NULL,
    Phonenumber    NVARCHAR(500) NOT NULL,
    CountryCode    NVARCHAR(500) NOT NULL,
    PhoneType      NVARCHAR(500) NOT NULL,
    PersonId       BIGINT NULL,
CONSTRAINT pk_Phone PRIMARY KEY CLUSTERED (PhoneId),
CONSTRAINT fk_Phone FOREIGN KEY (PersonId)
    REFERENCES Person (PersonId)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'AltAddress'   
-- PersonId        :  (references Person.PersonId)
-- AddressId       :  (references Address.AddressId)
-- AddressType     :  
--
CREATE TABLE AltAddress (
    PersonId       BIGINT NOT NULL,
    AddressId      BIGINT NOT NULL,
    AddressType    NVARCHAR(500) NOT NULL,
CONSTRAINT pk_AltAddress PRIMARY KEY CLUSTERED (PersonId,AddressId),
CONSTRAINT fk_AltAddress FOREIGN KEY (PersonId)
    REFERENCES Person (PersonId)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_AltAddress2 FOREIGN KEY (AddressId)
    REFERENCES Address (AddressId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO
