--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 29 2016 21:14
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'AltAddress'   
--
DROP TABLE AltAddress
GO
--
-- Drop Table    : 'Phone'   
--
DROP TABLE Phone
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
--
-- Drop Table    : 'Address'   
--
DROP TABLE Address
GO
