//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Personkartotek
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Address
	{
		public virtual int AddressId
		{
			get;
			set;
		}

		public virtual string Country
		{
			get;
			set;
		}

		public virtual string Street
		{
			get;
			set;
		}

		public virtual string Town
		{
			get;
			set;
		}

		public virtual string ZipCode
		{
			get;
			set;
		}

		public virtual IEnumerable<AddressElement> AdditionalOccupants
		{
			get;
			set;
		}

	}
}

