//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Personkartotek
{
    public class Phone
	{
		public virtual int CountryCode
		{
			get;
			set;
		}

		public virtual int PhoneId
		{
			get;
			set;
		}

		public virtual string Phonenumber
		{
			get;
			set;
		}

		public virtual string PhoneType
		{
			get;
			set;
		}

	}
}

